- id: 70f2d33d43304037baaf52f5cfa8c6e4
  alias: David - Workday Alarm
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (state_attr(''input_datetime.alarm_time_david'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: person.david
    state: home
  - condition: state
    entity_id: binary_sensor.workday_david
    state: 'on'
  action:
  - service: script.sonos_say
    data_template:
      sonos_entity: media_player.bedroom
      volume: 0.4
      message: Good Morning David! Time to wake up!
  - delay: 00:00:10
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom
      volume_level: 0.18
  - service: media_player.select_source
    data:
      entity_id: media_player.bedroom
      source: Summer Hits of the 80s Radio
  - delay: 00:50:00
  - service: media_player.media_stop
    data:
      entity_id: media_player.bedroom
  mode: single
- id: 837435e7dfd748d5b4379c031f5606f0
  alias: Sunset minus thirty minutes
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:15
  action:
  - service: script.sonos_announce
    data_template:
      message: '{{ [ "Preparing for sunset. Have a pleasant evening!",  "The sun will
        be setting shortly. Enjoy your evening!", "Here comes the night. Don''t worry!
        I will take care of the lights!", "Activating evening lights! Don''t stay
        up too late!", "That''s OK, You relax, I will take care of the lights." ]
        |random }}'
  mode: single
- id: storelastrain
  alias: Save the date and time of last rain
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: weather.home
  condition:
  - condition: template
    value_template: '{{ ''rainy'' in trigger.from_state.state or ''rainy'' in trigger.to_state.state
      }}'
  action:
  - service: input_datetime.set_datetime
    entity_id: input_datetime.last_rain
    data_template:
      datetime: '{{ now().strftime(''%Y-%m-%d %H:%M:%S'') }}'
  mode: single
- id: someone_heading_home
  alias: Heading Home
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: numeric_state
    entity_id:
    - proximity.david_home
    - proximity.amy_home
    below: '5'
    id: 5 miles
  - platform: numeric_state
    entity_id:
    - proximity.david_home
    - proximity.amy_home
    below: '30'
    id: 30 miles
  - platform: numeric_state
    entity_id:
    - proximity.david_home
    - proximity.amy_home
    below: '60'
    id: 60 miles
  - platform: numeric_state
    entity_id:
    - proximity.david_home
    - proximity.amy_home
    below: '100'
    id: 100 miles
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.attributes.dir_of_travel  == "towards" }}'
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: 5 miles
      sequence:
      - service: script.sonos_announce
        data_template:
          message: '{{trigger.to_state.object_id[:-5] | capitalize}} is less than
            5 miles away and heading home!'
    - conditions:
      - condition: trigger
        id: 30 miles
      sequence:
      - service: script.sonos_announce
        data_template:
          message: '{{trigger.to_state.object_id[:-5] | capitalize}} is less than
            30 miles away and heading home!'
    - conditions:
      - condition: trigger
        id: 60 miles
      sequence:
      - service: script.sonos_announce
        data_template:
          message: '{{trigger.to_state.object_id[:-5] | capitalize}} is less than
            60 miles away and heading home!'
    - conditions:
      - condition: trigger
        id: 100 miles
      sequence:
      - service: script.sonos_announce
        data_template:
          message: '{{trigger.to_state.object_id[:-5] | capitalize}} is less than
            100 miles away and heading home!'
    default: []
  mode: single
- id: New Device Tracked
  alias: New Device Tracked
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: event
    event_type: device_tracker_new_device
  condition: []
  action:
  - service: persistent_notification.create
    data_template:
      title: 'Newly tracked: {{trigger.event.data.entity_id}}

        '
      message: 'New device tracked: ({{trigger.event.data.entity_id}}) Host: {{trigger.event.data.host_name}}
        Mac-address: {{trigger.event.data.mac}} Data: {{trigger.event.data}}

        '
  mode: single
- id: Process Default Changes for Lights
  alias: Process Default Changes for Lights
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - entity_id: sensor.default_dining_room_table_lamp
    platform: state
  - entity_id: sensor.default_exterior_shop_light
    platform: state
  - entity_id: sensor.default_exterior_driveway_light
    platform: state
  - entity_id: sensor.default_living_room_table_lamps
    platform: state
  - entity_id: sensor.default_living_room_corner_lamp
    platform: state
  - entity_id: sensor.default_study_table_lamp
    platform: state
  - entity_id: sensor.default_bedroom_table_lamp
    platform: state
  - entity_id: sensor.default_guest_bedroom_table_lamp
    platform: state
  condition: []
  action:
  - service: script.set_light_to_default
    data:
      mysensor: '{{trigger.to_state.entity_id }}'
  mode: parallel
  max: 10
- id: Process Default Changes for Switches
  alias: Process Default Changes for Switches
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - entity_id: binary_sensor.default_studio_parlour_floor_lamp
    platform: state
  - entity_id: binary_sensor.default_porch
    platform: state
  - entity_id: binary_sensor.default_christmas_tree
    platform: state
  condition: []
  action:
  - service: script.set_switch_to_default
    data:
      mysensor: '{{trigger.to_state.entity_id }}'
  mode: parallel
  max: 10
- id: '1609085637484'
  alias: Someone has come home
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: person.amy
    to: home
  - platform: state
    entity_id: person.david
    to: home
  condition: []
  action:
  - service: script.arrive_home_anyone
    data: {}
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.amy" }}'
      sequence:
      - service: script.arrive_home_amy
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.david" }}'
      sequence:
      - service: script.arrive_home_david
        data: {}
    default: []
  mode: queued
  max: 5
- id: '1609091851036'
  alias: Monitor - Washing Machine
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: numeric_state
    entity_id: sensor.washer_power
    above: '15'
    for: 00:00:30
  - platform: numeric_state
    entity_id: sensor.washer_power
    below: '15'
    for: 00:02:00
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.washer_power
        above: '15'
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: Washing
      - service: switch.turn_on
        data:
          entity_id: switch.laundry_light
    - conditions:
      - condition: numeric_state
        entity_id: sensor.washer_power
        below: '15'
      - condition: state
        entity_id: input_select.state_washingmachine
        state: Washing
      sequence:
      - service: input_select.select_option
        data:
          entity_id: input_select.state_washingmachine
          option: Ready
      - service: script.sonos_announce
        data:
          message: The washing machine has finished and is ready to be emptied!
      - service: switch.turn_on
        data:
          entity_id: switch.laundry_light
    default: []
  mode: single
- id: '1609099392133'
  alias: Monitor - Shop Door
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.shop_door
  condition:
  - condition: state
    entity_id: binary_sensor.tod_overnight
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.exterior_shop_light
      brightness_pct: 100
  mode: single
- id: media_plex_stopped_lights_on
  alias: Plex Stopped - Lights On
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_roku_livingroom
    to: idle
    for:
      seconds: 3
  - platform: state
    entity_id: media_player.plex_plex_for_roku_livingroom
    to: paused
    for:
      seconds: 3
  condition:
  - condition: state
    entity_id: binary_sensor.tod_evening
    state: 'on'
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.plex_livingroom_playing
      state: music
  action:
  - service: script.set_light_to_default
    data:
      mysensor: sensor.default_living_room_table_lamps
  - service: script.set_light_to_default
    data:
      mysensor: sensor.default_living_room_corner_lamp
  mode: single
- id: media_plex_started_dim_lights
  alias: Plex Started - Dim Lights
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_roku_livingroom
    to: playing
  condition:
  - condition: state
    entity_id: binary_sensor.tod_evening
    state: 'on'
  - condition: not
    conditions:
    - condition: state
      entity_id: sensor.plex_livingroom_playing
      state: music
  action:
  - service: light.turn_off
    data:
      entity_id: light.living_room_table_lamps
  - service: light.turn_on
    data:
      entity_id: light.living_room_corner_lamp
      brightness_pct: 35
  mode: single
- id: '1634938317979'
  alias: Monitor - Office Phones
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.obihai_office_phone1_port
    id: Line 1
  - platform: state
    entity_id: sensor.obihai_office_phone2_port
    id: Line 2
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.office
      state: playing
    - condition: state
      entity_id: media_player.painting_room
      state: playing
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: Line 1
      - condition: state
        entity_id: sensor.obihai_office_phone1_port
        state: Off Hook
      sequence:
      - service: media_player.volume_mute
        target:
          device_id: 0328cc8388e54a3e88c53a3583d6ee0d
        data:
          is_volume_muted: true
    - conditions:
      - condition: trigger
        id: Line 1
      - condition: state
        entity_id: sensor.obihai_office_phone1_port
        state: On Hook
      sequence:
      - service: media_player.volume_mute
        target:
          device_id: 0328cc8388e54a3e88c53a3583d6ee0d
        data:
          is_volume_muted: false
    - conditions:
      - condition: trigger
        id: Line 2
      - condition: state
        entity_id: sensor.obihai_office_phone2_port
        state: Off Hook
      sequence:
      - service: media_player.volume_mute
        target:
          device_id: 7115c244f68a4bd393929693402d65f7
        data:
          is_volume_muted: true
    - conditions:
      - condition: trigger
        id: Line 2
      - condition: state
        entity_id: sensor.obihai_office_phone2_port
        state: On Hook
      sequence:
      - service: media_player.volume_mute
        target:
          device_id: 7115c244f68a4bd393929693402d65f7
        data:
          is_volume_muted: false
    default: []
  mode: single
- id: '1635272907255'
  alias: Timer - Lights and Switches
  description: ''
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.default_exterior_driveway_light'') != states(''sensor.brightness_exterior_driveway_light'')
      }}'
    id: Driveway
  - platform: template
    value_template: '{{ states(''sensor.default_exterior_shop_light'') != states(''sensor.brightness_exterior_shop_light'')
      }}'
    id: Shop
  - platform: template
    value_template: '{{ states(''binary_sensor.default_laundry_light'') != states(''switch.laundry_light'')
      }}'
    id: Laundry
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0
  - choose:
    - conditions:
      - condition: trigger
        id: Driveway
      sequence:
      - service: script.set_light_to_default
        data:
          mysensor: sensor.default_exterior_driveway_light
      - service: logbook.log
        data:
          name: '[damyBot] Light and Switch timer'
          message: Exterior driveway light returned to default brightness
          domain: logbook
    - conditions:
      - condition: trigger
        id: Shop
      sequence:
      - service: script.set_light_to_default
        data:
          mysensor: sensor.default_exterior_shop_light
      - service: logbook.log
        data:
          name: '[damyBot] Light and Switch timer'
          domain: logbook
          message: Exterior Shop light returned to default brightness
    - conditions:
      - condition: trigger
        id: Laundry
      sequence:
      - service: script.set_switch_to_default
        data:
          mysensor: binary_sensor.default_laundry_light
      - service: logbook.log
        data:
          name: '[damyBot] Light and Switch timer'
          domain: logbook
          message: Laundry light returned to default brightness
  mode: parallel
  max: 5
