- id: 70f2d33d43304037baaf52f5cfa8c6e4
  alias: David - Workday Alarm
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (state_attr(''input_datetime.alarm_time_david'',
      ''timestamp'') | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: person.david
    state: home
  - condition: state
    entity_id: binary_sensor.workday_david
    state: 'on'
  action:
  - service: script.tts_house
    data:
      tts_target: 1
      tts_speaker: media_player.bedroom
      tts_message: Good Morning David! Time to wake up!
  - delay: 00:00:10
  - service: media_player.volume_set
    data:
      entity_id: media_player.bedroom
      volume_level: 0.18
  - service: media_player.select_source
    data:
      entity_id: media_player.bedroom
      source: Summer Hits of the 80s Radio
  - delay: 00:50:00
  - service: media_player.media_stop
    data:
      entity_id: media_player.bedroom
  mode: single
- id: 837435e7dfd748d5b4379c031f5606f0
  alias: Sunset minus thirty minutes
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: sun
    event: sunset
    offset: -00:30:15
  action:
  - service: script.tts_house
    data_template:
      tts_broadcast: 1
      tts_message: '{{ [ "Preparing for sunset. Have a pleasant evening!",  "The sun will
        be setting shortly. Enjoy your evening!", "Here comes the night. Don''t worry!
        I will take care of the lights!", "Activating evening lights! Don''t stay
        up too late!", "That''s OK, You relax, I will take care of the lights." ]
        |random }}'
  - service: script.tts_studio
    data_template:
      tts_broadcast: 1
      tts_message: '{{ [ "Preparing for sunset. Have a pleasant evening!",  "The sun will
        be setting shortly. Enjoy your evening!", "Here comes the night. Don''t worry!
        I will take care of the lights!", "Activating evening lights! Don''t stay
        up too late!", "That''s OK, You relax, I will take care of the lights." ]
        |random }}'
  mode: single
- id: New Device Tracked
  alias: New Device Tracked
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: event
    event_type: device_tracker_new_device
  condition: []
  action:
  - service: persistent_notification.create
    data_template:
      title: 'Newly tracked: {{trigger.event.data.entity_id}}

        '
      message: 'New device tracked: ({{trigger.event.data.entity_id}}) Host: {{trigger.event.data.host_name}}
        Mac-address: {{trigger.event.data.mac}} Data: {{trigger.event.data}}

        '
  mode: single
- id: Process temperature changes for House
  alias: Monitor - Scheduled Temperature for House
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - entity_id: sensor.house_heat_schedule
    platform: state
  condition: []
  action:
  - service: script.set_heat_to_schedule
    data:
      mysensor: sensor.house_heat_schedule
  mode: single
- id: Alert when thermostat is turned off
  alias: Monitor - Thermostat turned off
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
    - platform: template
      value_template: '{{ state_attr(''climate.house_thermostat_control'',''system_mode'') == ''[0]/off''  }}'
  condition: []
  action:
  - service: script.tts_house
    data_template:
      tts_broadcast: 1
      tts_message: "WARNING! The thermostat has been turned off. The furnace will not be activated unless the thermostat has been turned back on. Warning! The thermostat has been turned off"
  mode: single
- id: Process Default Changes for Lights
  alias: Monitor - Default Lights
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - entity_id: sensor.default_dining_room_table_lamp
    platform: state
  - entity_id: sensor.default_exterior_shop_light
    platform: state
  - entity_id: sensor.default_exterior_driveway_light
    platform: state
  - entity_id: sensor.default_living_room_table_lamps
    platform: state
  - entity_id: sensor.default_living_room_corner_lamp
    platform: state
  - entity_id: sensor.default_study_table_lamp
    platform: state
  - entity_id: sensor.default_bedroom_table_lamp
    platform: state
  - entity_id: sensor.default_guest_bedroom_table_lamp
    platform: state
  - entity_id: sensor.default_guest_livingroom_floor_lamp
    platform: state
  - entity_id: sensor.default_master_bedroom_table_lamp_amy
    platform: state
  condition: []
  action:
  - service: script.set_light_to_default
    data:
      mysensor: '{{trigger.to_state.entity_id }}'
  mode: parallel
  max: 10
- id: Process Default Changes for Switches
  alias: Monitor - Default Switches
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - entity_id: binary_sensor.default_studio_parlour_floor_lamp
    platform: state
  - entity_id: binary_sensor.default_porch_outlet
    platform: state
  - entity_id: binary_sensor.default_upstairs_outlet
    platform: state
  - entity_id: binary_sensor.default_basement_outlet
    platform: state
  - entity_id: binary_sensor.default_christmas_tree_studio
    platform: state
  - entity_id: binary_sensor.default_holiday_lights_1
    platform: state
  condition: []
  action:
  - service: script.set_switch_to_default
    data:
      mysensor: '{{trigger.to_state.entity_id }}'
  mode: parallel
  max: 10
- id: '1609085637484'
  alias: Someone has come home
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: person.amy
    to: home
  - platform: state
    entity_id: person.david
    to: home
  condition: []
  action:
  - service: script.arrive_home_anyone
    data: {}
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.amy" }}'
      sequence:
      - service: script.arrive_home_amy
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.david" }}'
      sequence:
      - service: script.arrive_home_david
        data: {}
    default: []
  mode: queued
  max: 5
- id: '1609099392133'
  alias: Monitor - Shop Door
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door_contact
  condition:
  - condition: state
    entity_id: binary_sensor.tod_overnight
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.exterior_shop_light
      brightness_pct: 100
  mode: single
- id: Process motion detected in Laundry
  alias: Monitor - Laundry motion
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.laundry_motion_occupancy
    to: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.laundry_light
  mode: single
