- id: New Device Tracked
  alias: New Device Tracked
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: event
    event_type: device_tracker_new_device
  condition: []
  action:
  - service: persistent_notification.create
    data_template:
      title: 'Newly tracked: {{trigger.event.data.entity_id}}

        '
      message: 'New device tracked: ({{trigger.event.data.entity_id}}) Host: {{trigger.event.data.host_name}}
        Mac-address: {{trigger.event.data.mac}} Data: {{trigger.event.data}}

        '
  mode: single
- id: '1609085637484'
  alias: Someone has come home
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
#  - platform: state
#    entity_id: person.amy
#    to: home
  - platform: state
    entity_id: person.david
    to: home
  condition: []
  action:
  - service: script.arrive_home_anyone
    data: {}
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.amy" }}'
      sequence:
      - service: script.arrive_home_amy
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.to_state.entity_id == "person.david" }}'
      sequence:
      - service: script.arrive_home_david
        data: {}
    default: []
  mode: queued
  max: 5
- id: '1609099392133'
  alias: Monitor - Shop Door
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.basement_door_contact
  condition:
  - condition: state
    entity_id: binary_sensor.tod_overnight
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.exterior_shop_light
      brightness_pct: 100
  mode: single
- id: Process motion detected in Laundry
  alias: Monitor - Laundry motion
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.laundry_motion_occupancy
    to: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.laundry_light
  mode: single
- id: Process motion detected in Porch
  alias: Monitor - Porch motion
  description: =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  trigger:
  - platform: state
    entity_id: binary_sensor.porch_motion_occupancy
    to: 'on'
  condition: []
  action:
  - service: script.porch_light_brighten
  - service: script.sonos_broadcast
    data:
      v_speakers:
      - media_player.bedroom
      - media_player.dining_room
      - media_player.study
      v_speaker_master:
      - media_player.dining_room
      v_volume_level: 0.3
      v_media_details:
      - v_media_to_play: media-source://media_source/local/HousePorchBell.wav
  - service: script.sonos_broadcast
    data:
      v_speakers:
      - media_player.office
      - media_player.painting_room
      v_speaker_master:
      - media_player.office
      v_volume_level: 0.3
      v_media_details:
      - v_media_to_play: media-source://media_source/local/HousePorchBell.wav
  mode: single
- id: '1704753265568'
  alias: Awtrix current playing song
  description: Display Current song
  use_blueprint:
    path: GKXydoDmOpjL.yaml
    input:
      awtrix_light: 7356b4242d2c91414eb6ec9d80e6caf9
      media_player: media_player.office
      icon_in: '9266'
      repeat_text: '1'
      push_icon: '2'
      show_rainbow: false
      text_case: '2'
      display_type: '1'
      text_color:
      - 0
      - 128
      - 255
