homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: Imperial
  time_zone: America/New_York
  country: US 
  allowlist_external_dirs:
    - /config
    - /config/www/sounds
#  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks: !secret ip_trusted_network
    - type: homeassistant

frontend:
  themes: !include_dir_merge_named themes
config:
#updater:
history:
#energy:
media_source:

logbook:
  include:
    domains:
      - logbook
     
#map:
sun:
system_health:
mobile_app:

tts:
  - platform: google_translate
    service_name: google_say

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    scan_interval: 12
    new_device_defaults:
      track_new_devices: true
    hosts:
      hostname1: !secret ip_iPhone

person:
  - name: Amy
    id: alk123
    device_trackers:
      - device_tracker.nmap_tracker_84_b1_e4_59_d7_cd
      - device_tracker.hostname1
  - name: David
    id: djk123
    user_id: !secret home_assistant_user_account_id_david
    device_trackers:
      - device_tracker.sm_g990u2
      - device_tracker.nmap_tracker_96_c5_21_64_8d_b1

notify:
  - name: "david_work"
    platform: smtp
    server: !secret ip_modi
    port: 25
    encryption: none
    sender: !secret email_smtp_sender
    sender_name: !secret email_smtp_sender_name
    recipient: !secret email_david_work

  - name: "bruce_work"
    platform: smtp
    server: !secret ip_modi
    port: 25
    encryption: none
    sender: !secret email_smtp_sender
    sender_name: !secret email_smtp_sender_name
    recipient: !secret email_bruce_work
  
lutron_caseta:
  host: !secret ip_lutron_hub
  keyfile: /ssl/lutron/caseta.key
  certfile: /ssl/lutron/caseta.crt
  ca_certs: /ssl/lutron/caseta-bridge.crt

mqtt:
  sensor:
    - name: "Guest Livingroom Env Temperature"
      state_topic: "shellies/shellyht-E00AA7/sensor/temperature"
      device_class: temperature
      unit_of_measurement: '°F'
    - name: "Guest Livingroom Env Humidity"
      state_topic: "shellies/shellyht-E00AA7/sensor/humidity"
      device_class: humidity
      unit_of_measurement: '%'

    - name: "Office Env Temperature"
      state_topic: "shellies/shellyht-957035/sensor/temperature"
      device_class: temperature
      unit_of_measurement: '°F'
    - name: "Office Env Humidity"
      state_topic: "shellies/shellyht-957035/sensor/humidity"
      device_class: humidity
      unit_of_measurement: '%'

    - name: "SpectrumPing"
      state_topic: "modi/speedtest/ping"
      value_template: "{{ value | float }}"
      unit_of_measurement: 'ms'
    - name: "SpectrumDown"
      state_topic: "modi/speedtest/download"
      value_template: "{{ value | float }}"
      unit_of_measurement: 'Mbps'
    - name: "SpectrumUp"
      state_topic: "modi/speedtest/upload"
      value_template: "{{ value | float }}"
      unit_of_measurement: 'Mbps'

proximity:
  david_home:
    zone: home
    devices:
      - device_tracker.sm_g990u2
    tolerance: 50
    unit_of_measurement: mi
#  amy_home:
#    zone: home
#    devices:
#      - device_tracker.life360_amy
#    tolerance: 50
#    unit_of_measurement: mi

sonoff:
  username: !secret ewe_username
  password: !secret ewe_password
  mode: local
  reload: always  # update device list every time HA starts
  force_update: [power]
  scan_interval: '00:01:00'  # (optional) default 5 minutes
  sensors: [power, current, voltage]

utility_meter:
  daily_steps:
    source: sensor.sm_g990u2_steps_sensor
    cycle: daily

### Includes ###
#alert: !include_dir_merge_named alerts/
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
binary_sensor: !include_dir_merge_list binary_sensors
#light: !include lights.yaml
#switch: !include switches.yaml
#scene: !include scenes.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
group: !include groups.yaml
zone: !include zones.yaml
