- platform: template
  sensors:
    house_heat_schedule:
      friendly_name: "House Heat Schedule"
      value_template: >-
        {% if is_state('binary_sensor.tod_heat_lunch','on') %}
          64
        {% elif is_state('binary_sensor.tod_heat_afternoon','on') %}
          62
        {% elif is_state('binary_sensor.tod_heat_evening','on') %}
          66
        {% elif is_state('binary_sensor.tod_amy_workday_morning','on') and is_state('binary_sensor.workday_amy','on') and is_state('person.amy','home') %}
          62
        {% else %}
          61
        {% endif %}
