- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: pushbullet
  api_key: !secret pushbullet_api_key
  monitored_conditions:
    - type

#- platform: github
#  access_token: !secret github_access_token
#  repositories:
#    - path: !secret github_repo

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
#    - type: throughput_network_in
#      arg: eth0
#    - type: throughput_network_out
#      arg: eth0
#    - type: processor_temperature

#- platform: filesize
#  file_paths:
#    - /config/home-assistant_v2.db
#    - /config/home-assistant.log

- platform: obihai
  host: !secret ip_obihai_office
  username: !secret obihai_username
  password: !secret obihai_password

- platform: obihai
  host: !secret ip_obihai_guest
  username: !secret obihai_username
  password: !secret obihai_password

#- platform: snmp
#  host: !secret ip_modi
#  community: public
#  name: Synology Uptime
#  baseoid: 1.3.6.1.2.1.25.1.1.0
#  version: '2c'
#  value_template: >
#    {%- set time = value | int // 100 %}
#    {%- set minutes = ((time % 3600) // 60) %}
#    {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
#    {%- set hours = ((time % 86400) // 3600) %}
#    {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
#    {%- set days = (time // 86400) %}
#    {%- set days = '{}d '.format(days) if days > 0 else '' %}
#    {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}
      
#- platform: snmp
#  host: !secret ip_modi
#  community: public
#  name: Synology DSM Version
#  baseoid: 1.3.6.1.4.1.6574.1.5.3.0
#  version: '2c'

#- platform: snmp
#  host: !secret ip_modi
#  community: public
#  name: Synology System Status
#  baseoid: 1.3.6.1.4.1.6574.1.1.0
#  version: '2c'
#  value_template: >
#    {% set status = value | int %}
#    {% if status == 1 %}
#    Normal
#    {% elif status == 2 %}
#    Failed
#    {% else %}
#    --- 
#    {% endif %}

#- platform: snmp
#  host: !secret ip_modi
#  community: public
#  name: Synology System Fan Status
#  baseoid: 1.3.6.1.4.1.6574.1.4.1.0
#  version: '2c'
#  value_template: >
#    {% set status = value | int %}
#    {% if status == 1 %}
#    Normal
#    {% elif status == 2 %}
#    Failed
#    {% else %}
#    --- 
#    {% endif %}

#- platform: snmp
#  host: !secret ip_modi
#  community: public
#  name: Synology CPU Fan Status
#  baseoid: 1.3.6.1.4.1.6574.1.4.2.0
#  version: '2c'
#  value_template: >
#    {% set status = value | int %}
#    {% if status == 1 %}
#    Normal
#    {% elif status == 2 %}
#    Failed
#    {% else %}
#    --- 
#    {% endif %}