- platform: moon
- platform: season
- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: pushbullet
  api_key: !secret pushbullet_api_key
  monitored_conditions:
    - type

- platform: version
  name: Installed
  source: local

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_use_percent
    - type: processor_use
    - type: last_boot
    - type: load_5m
    - type: throughput_network_in
      arg: eth0
    - type: throughput_network_out
      arg: eth0
    - type: processor_temperature

- platform: filesize
  file_paths:
    - /config/home-assistant_v2.db
    - /config/home-assistant.log

- platform: obihai
  host: !secret ip_obihai_office
  username: !secret obihai_username
  password: !secret obihai_password

- platform: obihai
  host: !secret ip_obihai_guest
  username: !secret obihai_username
  password: !secret obihai_password

- platform: mqtt
  name: "Shelly HT Temp"
  state_topic: "shellies/shellyht-E00AA7/sensor/temperature"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Shelly HT Humidity"
  state_topic: "shellies/shellyht-E00AA7/sensor/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "Shelly HT Battery"
  state_topic: "shellies/shellyht-E00AA7/sensor/battery"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "Shelly HT002 Temp"
  state_topic: "shellies/shellyht-957035/sensor/temperature"
  device_class: temperature
  unit_of_measurement: '°F'
- platform: mqtt
  name: "Shelly HT002 Humidity"
  state_topic: "shellies/shellyht-957035/sensor/humidity"
  device_class: humidity
  unit_of_measurement: '%'
- platform: mqtt
  name: "Shelly HT002 Battery"
  state_topic: "shellies/shellyht-957035/sensor/battery"
  device_class: battery
  unit_of_measurement: '%'

- platform: mqtt
  name: "SpectrumPing"
  state_topic: "modi/speedtest/ping"
  value_template: "{{ value | float }}"
  unit_of_measurement: 'ms'
- platform: mqtt
  name: "SpectrumDown"
  state_topic: "modi/speedtest/download"
  value_template: "{{ value | float }}"
  unit_of_measurement: 'Mbps'
- platform: mqtt
  name: "SpectrumUp"
  state_topic: "modi/speedtest/upload"
  value_template: "{{ value | float }}"
  unit_of_measurement: 'Mbps'

- platform: snmp
  host: !secret ip_modi
  community: public
  name: Synology Uptime
  baseoid: 1.3.6.1.2.1.25.1.1.0
  version: '2c'
  value_template: >
    {%- set time = value | int // 100 %}
    {%- set minutes = ((time % 3600) // 60) %}
    {%- set minutes = '{}min'.format(minutes) if minutes > 0 else '' %}
    {%- set hours = ((time % 86400) // 3600) %}
    {%- set hours = '{}hr '.format(hours) if hours > 0 else '' %}
    {%- set days = (time // 86400) %}
    {%- set days = '{}d '.format(days) if days > 0 else '' %}
    {{ 'Less than 1 min' if time < 60 else days + hours + minutes }}
      
- platform: snmp
  host: !secret ip_modi
  community: public
  name: Synology DSM Version
  baseoid: 1.3.6.1.4.1.6574.1.5.3.0
  version: '2c'

- platform: snmp
  host: !secret ip_modi
  community: public
  name: Synology System Status
  baseoid: 1.3.6.1.4.1.6574.1.1.0
  version: '2c'
  value_template: >
    {% set status = value | int %}
    {% if status == 1 %}
    Normal
    {% elif status == 2 %}
    Failed
    {% else %}
    --- 
    {% endif %}

- platform: snmp
  host: !secret ip_modi
  community: public
  name: Synology System Fan Status
  baseoid: 1.3.6.1.4.1.6574.1.4.1.0
  version: '2c'
  value_template: >
    {% set status = value | int %}
    {% if status == 1 %}
    Normal
    {% elif status == 2 %}
    Failed
    {% else %}
    --- 
    {% endif %}

- platform: snmp
  host: !secret ip_modi
  community: public
  name: Synology CPU Fan Status
  baseoid: 1.3.6.1.4.1.6574.1.4.2.0
  version: '2c'
  value_template: >
    {% set status = value | int %}
    {% if status == 1 %}
    Normal
    {% elif status == 2 %}
    Failed
    {% else %}
    --- 
    {% endif %}

- platform: template
  sensors:
    plex_livingroom_playing:
      friendly_name: 'Currently Playing on Plex - Livingroom'
      value_template: "{{ state_attr('media_player.plex_plex_for_roku_livingroom', 'media_content_type') }}"

    today_is:
      friendly_name: 'Today is'
      value_template: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}" 

    battery_david:
      friendly_name: "David's Battery"
      value_template: "{{ state_attr('device_tracker.life360_david', 'battery') }}"
      unit_of_measurement: '%'
      device_class: battery

    battery_charging_david:
      friendly_name: "David's Phone is Charging"
      value_template: "{{ state_attr('device_tracker.life360_david', 'battery_charging') }}"

    battery_ken:
      friendly_name: "Ken's Battery"
      value_template: "{{ state_attr('device_tracker.life360_ken_howard', 'battery') }}"
      unit_of_measurement: '%'
      device_class: battery

    battery_charging_ken:
      friendly_name: "Ken's Phone is Charging"
      value_template: "{{ state_attr('device_tracker.life360_ken_howard', 'battery_charging') }}"

    battery_nexus:
      friendly_name: "Nexus 7 Battery"
      value_template: "{{ state_attr('device_tracker.nexus_7', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery

    battery_amy:
      friendly_name: Amy's Battery
      value_template: "{{ state_attr('device_tracker.life360_amy', 'battery') }}"
      unit_of_measurement: '%'
      device_class: battery

    battery_charging_amy:
      friendly_name: "Amy's Phone is Charging"
      value_template: "{{ state_attr('device_tracker.life360_amy', 'battery_charging') }}"

    sonos_office_volume:
      value_template: "{{ state_attr('media_player.office', 'volume_level') }}"

    sonos_bedroom_volume:
      value_template: "{{ state_attr('media_player.bedroom', 'volume_level') }}"

    sonos_study_volume:
      value_template: "{{ state_attr('media_player.study', 'volume_level') }}"

    sonos_painting_room_volume:
      value_template: "{{ state_attr('media_player.painting_room', 'volume_level') }}"

#    sonos_dining_room_volume:
#      value_template: "{{ state_attr('media_player.dining_room', 'volume_level') }}"

    sonos_living_room_volume:
      value_template: "{{ state_attr('media_player.living_room', 'volume_level') }}"

#####

    brightness_exterior_shop_light:
      friendly_name: "Brightness - Exterior Shop Light"
      value_template: >
        {% if state_attr('light.exterior_shop_light', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.exterior_shop_light', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_exterior_driveway_light:
      friendly_name: "Brightness - Exterior Driveway Light"
      value_template: >
        {% if state_attr('light.exterior_driveway_light', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.exterior_driveway_light', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_living_room_table_lamps:
      friendly_name: "Brightness - Living Room Table Lamps"
      value_template: >
        {% if state_attr('light.living_room_table_lamps', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.living_room_table_lamps', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_living_room_corner_lamp:
      friendly_name: "Brightness - Living Room Corner Lamp"
      value_template: >
        {% if state_attr('light.living_room_corner_lamp', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.living_room_corner_lamp', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_dining_room_ceiling_light:
      friendly_name: "Brightness - Dining Room Ceiling Light"
      value_template: >
        {% if state_attr('light.dining_room_ceiling_light', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.dining_room_ceiling_light', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_dining_room_table_lamp:
      friendly_name: "Brightness - Dining Room Table Lamp"
      value_template: >
        {% if state_attr('light.dining_room_table_lamp', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.dining_room_table_lamp', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_study_ceiling_light:
      friendly_name: "Brightness - Study Ceiling Light"
      value_template: >
        {% if state_attr('light.study_ceiling_light', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.study_ceiling_light', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_study_table_lamp:
      friendly_name: "Brightness - Study Table Lamp"
      value_template: >
        {% if state_attr('light.study_table_lamp', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.study_table_lamp', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_bedroom_table_lamp:
      friendly_name: "Brightness - Bedroom Table Lamp"
      value_template: >
        {% if state_attr('light.bedroom_table_lamp', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.bedroom_table_lamp', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_guest_livingroom_ceiling_light:
      friendly_name: "Brightness - Guest Livingroom Ceiling Light"
      value_template: >
        {% if state_attr('light.guest_livingroom_ceiling_light', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.guest_livingroom_ceiling_light', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'

    brightness_guest_bedroom_table_lamp:
      friendly_name: "Brightness - Guest Bedroom Table Lamp"
      value_template: >
        {% if state_attr('light.guest_bedroom_table_lamp', 'brightness')|string != 'None' %}
          {{ ((state_attr('light.guest_bedroom_table_lamp', 'brightness')/255)*100 | int ) | round(0) }}
        {% else %}
          0
        {% endif %}
      unit_of_measurement: '%'
###

    nextsunrise:
      friendly_name: 'Next Sunrise'
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_rising) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
      icon_template: mdi:weather-sunset-up

    nextsunset:
      friendly_name: 'Next Sunset'
      value_template: >
        {{ as_timestamp(states.sun.sun.attributes.next_setting) | timestamp_custom(' %I:%M %p') | replace(" 0", "") }}
      icon_template: mdi:weather-sunset-down

    hass_count:
      friendly_name: HASS Count
      icon_template: mdi:home-assistant
      value_template: "{{ states | count }}"
      attribute_templates:
        automation: "{{ states.automation | count }}"
        binary_sensor: "{{ states.binary_sensor | count }}"
#        camera: "{{ states.camera | count }}"
#        climate: "{{ states.climate | count }}"
        device_tracker: "{{ states.device_tracker | count }}"
        light: "{{ states.light | count }}"
        media_player: "{{ states.media_player | count }}"
        scene: "{{ states.scene | count }}"
        script: "{{ states.script | count }}"
        sensor: "{{ states.sensor | count }}"
        switch: "{{ states.switch | count }}"

    default_dining_room_ceiling_light:
      friendly_name: "Default - Dining Room Ceiling Light"
      value_template: >-
          0

    default_dining_room_table_lamp:
      friendly_name: "Default - Dining Room Table Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') %}
          20
        {% else %}
          0
        {% endif %}

    default_exterior_shop_light:
      friendly_name: "Default - Exterior Shop Light"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') %}
          20
        {% else %}
          0
        {% endif %}

    default_exterior_driveway_light:
      friendly_name: "Default - Exterior Driveway Light"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') %}
          12
        {% else %}
          0
        {% endif %}

    default_living_room_table_lamps:
      friendly_name: "Default - Living Room Table Lamps"
      value_template: >-
        {% if is_state('binary_sensor.tod_evening','on') and is_state('group.amy_or_david','home') %}
          35
        {% else %}
          0
        {% endif %}

    default_study_table_lamp:
      friendly_name: "Default - Study Table Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_evening','on') %}
          20
        {% else %}
          0
        {% endif %}

    default_living_room_corner_lamp:
      friendly_name: "Default - Living Room Corner Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_evening','on') %}
          20
        {% elif is_state('binary_sensor.tod_morning','on') and is_state('binary_sensor.workday_amy','on') and is_state('person.amy','home') %}
          20
        {% else %}
          0
        {% endif %}

    default_study_ceiling_light:
      friendly_name: "Default - Study Ceiling Light"
      value_template: >-
          0

    default_bedroom_table_lamp:
      friendly_name: "Default - Bedroom Table Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') and is_state('group.amy_or_david','home') %}
          18
        {% else %}
          0
        {% endif %}

    default_guest_livingroom_ceiling_light:
      friendly_name: "Default - Guest Livingroom Ceiling Light"
      value_template: >-
          0

    default_guest_bedroom_table_lamp:
      friendly_name: "Default - Guest Bedroom Table Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') and is_state('binary_sensor.guest_mode','on') %}
          22
        {% else %}
          0
        {% endif %}

    temperature_accuweather:
      friendly_name: "Temperature - Outside"
      value_template: >
          {{ state_attr('weather.home', 'temperature') }}
      unit_of_measurement: '°F'

    doors_open_count:
      friendly_name: Number of doors open
      icon_template: mdi:door-open
      value_template: >-
        {{ states.binary_sensor 
        | selectattr('attributes.device_class', 'eq', 'door')
        | selectattr('state', 'eq', 'on')
        | list | length }}

    lights_on_count:
      friendly_name: Number of lights on
      icon_template: mdi:lightbulb-on-outline
      value_template: >-
        {{ states.light | selectattr('state', 'eq', 'on') | list | length }}

    people_home_count:
      friendly_name: Number of people at home
      icon_template: mdi:account-multiple
      value_template: >-
        {{ states.person | selectattr('state', 'eq', 'home') | list | length }}
