- platform: time_date
  display_options:
    - 'time'
    - 'date'

- platform: snmp
  name: Dell Printer Name
  host: 10.10.10.33
  baseoid: iso.3.6.1.2.1.25.3.2.1.3.1
  accept_errors: true
  scan_interval: 86400
  value_template: "{{ value.split(';')[0] }}"

- platform: snmp
  name: Dell Printer Uptime
  host: 10.10.10.33
  baseoid: 1.3.6.1.2.1.1.3.0
  accept_errors: true
  scan_interval: 3600
  unit_of_measurement: 'Days'
  value_template: "{{ (value | int / 8640000) | int }}"

- platform: snmp
  name: Dell Printer Printed
  host: 10.10.10.33
  baseoid: iso.3.6.1.2.1.43.10.2.1.4.1.1
  accept_errors: true
  scan_interval: 3600