- platform: template
  sensors:
    default_studio_parlour_floor_lamp:
      friendly_name: "Default - Studio Parlour Floor Lamp"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on') and is_state('binary_sensor.guest_mode','on') %}
          on
        {% elif is_state('binary_sensor.tod_evening','on') %}
          on
        {% else %}
          off
        {% endif %}
   
    default_laundry_light:
      friendly_name: "Default - Laundry Light"
      value_template: >-
          off

    default_christmas_tree_studio:
      friendly_name: "Default - Studio Christmas Tree"
      value_template: >-
        {{ is_state('binary_sensor.tod_evening','on') }}

    default_holiday_lights_1:
      friendly_name: "Default - Holiday Lights 1"
      value_template: >-
        off

    default_porch_outlet_control:
      friendly_name: "Default - Porch Outlet Control"
      value_template: >-
        {{ is_state('binary_sensor.tod_evening','on') }}

    default_upstairs_outlet_control:
      friendly_name: "Default - Upstairs Outlet Control"
      value_template: >-
        {% if is_state('binary_sensor.tod_overnight','on')  %}
          on
        {% elif is_state('binary_sensor.tod_evening','on') %}
          on
        {% else %}
          off
        {% endif %}

    default_living_room_outlet_control:
      friendly_name: "Default - Living Room Outlet Control"
      value_template: >-
        {% if is_state('light.living_room_table_lamps','on')  %}
          off
        {% elif is_state('binary_sensor.tod_overnight','on')  %}
          on
        {% elif is_state('binary_sensor.tod_evening','on') %}
          on
        {% else %}
          off
        {% endif %}

