- platform: tod
  name: "TOD Overnight"
  after: sunset
  before: sunrise

- platform: tod
  name: "TOD Evening"
  after: sunset
  after_offset:  "-00:30:00"
  before: "22:20"

- platform: tod
  name: "The Hour of the Wolf"
  after: '03:00'
  before: '04:00'

- platform: tod
  name: "TOD Daytime"
  after: sunrise
  before: sunset

- platform: tod
  name: "TOD Morning"
  after: sunrise
  before: "12:00"

- platform: tod
  name: "TOD Afternoon"
  after: "12:00"
  before: sunset

- platform: tod
  name: "TOD Amy Workday Morning"
  after: "04:30"
  after_offset: "+01:00:00"
  before: sunrise
  before_offset: "+00:20:00"

- platform: tod
  name: "TOD Announce"
  after: '07:01'
  before: '21:00'

- platform: tod
  name: "TOD Chimes"
  after: '07:55'
  before: '20:05'

- platform: tod
  name: "TOD Holiday Lights"
  after: '15:00'
  before: '21:45'

- platform: tod
  name: "TOD Heat Overnight"
  after: '22:30'
  before: '11:45'

- platform: tod
  name: "TOD Heat Lunch"
  after: '11:50'
  before: '12:50'

- platform: tod
  name: "TOD Heat Afternoon"
  after: '12:50'
  before: '16:45'

- platform: tod
  name: "TOD Heat Evening"
  after: '16:45'
  before: '21:45'
